---
- name: Install apps
  hosts: localhost

  tasks:
    - name: Install apt packages
      apt:
        name: 
          - terminator
          - git
          - python3-pip
          - hdf5-tools
          - zsh
        state: present
        update_cache: yes
      become: true
    
    - name: Snap install slack
      snap:
        name: 
        - slack
        - spotify
        state: present
      become: true

    

