---
- name: Install terminator
  hosts: localhost

  tasks:
    - name: Install terminator
      apt:
        name: 
          - terminator
          - git
          - python3-pip











          - hdf5-tools
        state: present
        update_cache: yes
      become: true
    
    - name: Snap install slack
      snap:
        name: 
        - slack
        - spotify
        state: present
      become: true

    

